#!/usr/bin/env python3
"""Prototype: build the same sprite sheet from SVG instead of Blender.

    art/svg/render_prototype.py <output directory>

This is a prototype, not the shipped pipeline. It exists so the two media
can be compared on the same contract: it writes units.png, units_mask.png
and units.json exactly as art/blender/render_sprites.py does, for whichever
units have an SVG. Nothing in client/ points at it.

The point it is meant to prove: everything downstream of the sheet - the
mask, the manifest, the tint shader, sprite_check, sprite_preview - does not
know or care what drew the pixels. Only the producer changes.

The mask is free here in a way it is not in Blender. There, it is a second
render with every material swapped. Here it is the same file with one extra
stylesheet appended, so the two passes cannot drift apart: a shape is
faction-coloured if and only if its class says so.

Needs rsvg-convert (librsvg2-bin). Neither Godot nor the game needs it; the
sheet is committed.
"""

import json
import os
import re
import struct
import subprocess
import sys
import tempfile
import zlib

CELL = 64
TILE = 48
HERE = os.path.dirname(os.path.abspath(__file__))

# Appended after the file's own <style>, so it wins on specificity ties by
# being later. Faction classes go white, everything else black.
MASK_STYLE = """
<style>
.team-hi,.team,.team-lo{fill:#ffffff;stroke:#ffffff}
.dark,.dark-hi,.light,.glass{fill:#000000;stroke:#000000}
.edge{stroke-width:0.7}
.barrel,.rifle,.skid,.blade{stroke:#000000}
</style>
"""


def rasterise(svg_path, out_path, mask=False):
    source = open(svg_path).read()
    if mask:
        # Insert immediately before </svg> so it is the last stylesheet.
        source = source.replace("</svg>", MASK_STYLE + "</svg>")
    with tempfile.NamedTemporaryFile("w", suffix=".svg", delete=False) as handle:
        handle.write(source)
        temp = handle.name
    try:
        subprocess.run(
            ["rsvg-convert", "-w", str(CELL), "-h", str(CELL), "-o", out_path, temp],
            check=True, capture_output=True)
    finally:
        os.unlink(temp)


def decode(path):
    """Minimal 8-bit RGBA PNG reader - the same one tools/compare_sheets.py uses."""
    sys.path.insert(0, os.path.join(HERE, "..", "..", "tools"))
    from compare_sheets import decode as _decode
    return _decode(path)


def write_png(path, width, height, pixels):
    raw = b"".join(b"\x00" + pixels[y * width * 4:(y + 1) * width * 4] for y in range(height))
    def chunk(kind, body):
        return struct.pack(">I", len(body)) + kind + body + struct.pack(">I", zlib.crc32(kind + body))
    with open(path, "wb") as handle:
        handle.write(b"\x89PNG\r\n\x1a\n")
        handle.write(chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0)))
        handle.write(chunk(b"IDAT", zlib.compress(raw, 9)))
        handle.write(chunk(b"IEND", b""))


def strip(paths, out_path):
    frames = [decode(p) for p in paths]
    width = CELL * len(frames)
    out = bytearray(width * CELL * 4)
    for index, (fw, fh, px) in enumerate(frames):
        assert (fw, fh) == (CELL, CELL), "%s is %dx%d" % (paths[index], fw, fh)
        for y in range(CELL):
            start = (y * width + index * CELL) * 4
            out[start:start + CELL * 4] = px[y * CELL * 4:(y + 1) * CELL * 4]
    write_png(out_path, width, CELL, bytes(out))


def main():
    if len(sys.argv) != 2:
        raise SystemExit("usage: render_prototype.py <output directory>")
    out_dir = sys.argv[1]
    os.makedirs(out_dir, exist_ok=True)

    root = os.path.dirname(os.path.dirname(HERE))
    with open(os.path.join(root, "shared", "data", "units.json")) as handle:
        table = json.load(handle)["units"]
    # Shared-table order, same as the Blender renderer, restricted to the
    # units that have been drawn. A real switch-over would fail on a missing
    # one instead of skipping it.
    order = [name for name in table if os.path.exists(os.path.join(HERE, name + ".svg"))]
    if not order:
        raise SystemExit("no unit SVGs in %s" % HERE)

    with tempfile.TemporaryDirectory() as scratch:
        for mask in (False, True):
            parts = []
            for name in order:
                target = os.path.join(scratch, "%s%s.png" % (name, "_mask" if mask else ""))
                rasterise(os.path.join(HERE, name + ".svg"), target, mask=mask)
                parts.append(target)
            strip(parts, os.path.join(out_dir, "units_mask.png" if mask else "units.png"))

    manifest = {
        "_comment": "Generated by art/svg/render_prototype.py - the SVG prototype,"
                    " not the shipped sheet.",
        "tile": TILE, "cell": CELL, "sheet": "units.png", "mask": "units_mask.png",
        "width": CELL * len(order), "height": CELL,
        "frames": {name: index for index, name in enumerate(order)},
    }
    with open(os.path.join(out_dir, "units.json"), "w") as handle:
        json.dump(manifest, handle, indent=2, sort_keys=True)
        handle.write("\n")
    print("SVG_SPRITES_OK %d units -> %s" % (len(order), out_dir))


main()
